name: chuck_example
description: Demonstrates how to use the Chuck Interceptor plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  chuck_interceptor:
    path: ../

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
